# -*- coding: utf-8 -*-
"""handgesturesfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7w_yvjhvHc0-ECIul2LiWQzmvYMTfx2
"""

# INSTALL LIBRARIES (Google Colab)
!pip install mediapipe opencv-python tensorflow scikit-learn gradio

# PHASE 1 — DATA PROCESSING
# STEP 1 — Import Libraries
import os
import cv2
import mediapipe as mp
import numpy as np
import pandas as pd

# Download the hand landmarker model asset
!wget -q -O hand_landmarker.task https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task

# STEP 2 — Initialize MediaPipe HandLandmarker
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# Before running this cell, make sure to download the model asset.
# You can use the following command in a new code cell:
# !wget -q -O hand_landmarker.task https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task

base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')

# Options for HandLandmarker
# The parameters from the old API are mapped to the new API as follows:
# - static_image_mode is implicitly handled by using 'detect()' for static images.
# - max_num_hands corresponds to num_hands.
# - min_detection_confidence corresponds to min_hand_detection_confidence.
options = vision.HandLandmarkerOptions(
    base_options=base_options,
    num_hands=1,
    min_hand_detection_confidence=0.5
)

# Create a HandLandmarker object
hand_landmarker = vision.HandLandmarker.create_from_options(options)

# STEP 5 — Landmark Extraction Function
def extract_landmarks(image_path):
    image = cv2.imread(image_path)

    if image is None:
        return None

    # Convert the BGR image to RGB and then to MediaPipe Image format
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image_rgb)

    # Perform hand landmark detection
    # The 'hand_landmarker' object was initialized in a previous cell.
    detection_result = hand_landmarker.detect(mp_image)

    # Check if any hand landmarks were detected
    if not detection_result.hand_landmarks:
        return None

    landmarks = []

    # We are interested in the first detected hand
    hand_landmarks = detection_result.hand_landmarks[0]

    for lm in hand_landmarks:
        landmarks.append(lm.x)
        landmarks.append(lm.y)

    return landmarks

# STEP 6 — Load Dataset
import zipfile

zip_path = "/content/hand gestures recognition.zip"
extract_path = "/content/hand_gestures_data"

# Unzip the dataset if it hasn't been unzipped already
if not os.path.exists(extract_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print(f"Dataset unzipped to: {extract_path}")

dataset_path = extract_path

X = []
y = []

# List directories inside the extracted path, assuming each is a class
classes = [d for d in os.listdir(dataset_path) if os.path.isdir(os.path.join(dataset_path, d))]

for label in classes:
    class_path = os.path.join(dataset_path, label)

    for img_name in os.listdir(class_path):
        img_path = os.path.join(class_path, img_name)

        landmarks = extract_landmarks(img_path)

        if landmarks is not None:
            X.append(landmarks)
            y.append(label)

print("Total Samples:", len(X))
print("Classes found:", classes)

# STEP 7 — Convert to NumPy Arrays
X = np.array(X)
y = np.array(y)

print(X.shape)
print(y.shape)

# STEP 8 — Normalize Features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(X)

# PHASE 2 — DATA SPLITTING & MODEL SELECTION
# STEP 9 — Encode Labels
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y_encoded = encoder.fit_transform(y)

# STEP 10 — Train/Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print(X_train.shape)
print(X_test.shape)

# PHASE 3 — TRAINING & EVALUATION
# MODEL 1 — Dense Neural Network
# STEP 11 — Build Neural Network
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

num_classes = len(np.unique(y_encoded))

model = Sequential([

    Dense(128, activation='relu', input_shape=(42,)),

    Dropout(0.3),

    Dense(64, activation='relu'),

    Dropout(0.2),

    Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# STEP 12 — Early Stopping
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

# STEP 13 — Train Model
history = model.fit(

    X_train,
    y_train,

    validation_data=(X_test, y_test),

    epochs=50,

    batch_size=16,

    callbacks=[early_stop]
)

# STEP 14 — Evaluate Accuracy
loss, accuracy = model.evaluate(X_test, y_test)

print(f"Test Accuracy: {accuracy*100:.2f}%")

# STEP 15 — Predictions
y_pred = model.predict(X_test)

y_pred = np.argmax(y_pred, axis=1)

# STEP 16 — Classification Report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

classes = list(encoder.classes_)

print(classes)

print(encoder.classes_)

classes = list(encoder.classes_)

# Dynamically find an image path from the 'greet' directory
greet_dir = os.path.join(extract_path, 'greet')

img_path = None
# Check if the directory exists and is not empty
if os.path.exists(greet_dir) and os.listdir(greet_dir):
    # Get the first image filename in the 'greet' directory
    img_filename = os.listdir(greet_dir)[0]
    img_path = os.path.join(greet_dir, img_filename)
else:
    raise FileNotFoundError(f"Error: Directory {greet_dir} not found or is empty. Cannot find an image for prediction.")

print(f"Attempting to predict using image: {img_path}")

# Re-initialize MediaPipe HandLandmarker to ensure it's running
# This addresses potential issues where the global hand_landmarker might have been closed
# or an inconsistent kernel state led to the 'Task runner is currently not running' error.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
options = vision.HandLandmarkerOptions(
    base_options=base_options,
    num_hands=1,
    min_hand_detection_confidence=0.5
)
global hand_landmarker # Declare global to modify the global variable
hand_landmarker = vision.HandLandmarker.create_from_options(options)

# Extract landmarks using the predefined function
landmarks = extract_landmarks(img_path)

if landmarks is None:
    print(f"No hand landmarks detected in image: {img_path}")
else:
    # Convert list of landmarks to numpy array and reshape for the model
    landmarks_array = np.array(landmarks).reshape(1, -1)

    # Scale the landmarks using the trained scaler
    scaled_landmarks = scaler.transform(landmarks_array)

    # Make prediction
    prediction = model.predict(scaled_landmarks)

    predicted_index = np.argmax(prediction)

    predicted_class = classes[predicted_index]

    confidence = np.max(prediction) * 100

    print("Prediction:", predicted_class)
    print("Confidence:", confidence)

classes = list(encoder.classes_)

# Dynamically find an image path from the 'pointing' directory
greet_dir = os.path.join(extract_path, 'pointing')

img_path = None
# Check if the directory exists and is not empty
if os.path.exists(greet_dir) and os.listdir(greet_dir):
    # Get the first image filename in the 'pointing' directory
    img_filename = os.listdir(greet_dir)[0]
    img_path = os.path.join(greet_dir, img_filename)
else:
    raise FileNotFoundError(f"Error: Directory {greet_dir} not found or is empty. Cannot find an image for prediction.")

print(f"Attempting to predict using image: {img_path}")

# Re-initialize MediaPipe HandLandmarker to ensure it's running
# This addresses potential issues where the global hand_landmarker might have been closed
# or an inconsistent kernel state led to the 'Task runner is currently not running' error.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
options = vision.HandLandmarkerOptions(
    base_options=base_options,
    num_hands=1,
    min_hand_detection_confidence=0.5
)
global hand_landmarker # Declare global to modify the global variable
hand_landmarker = vision.HandLandmarker.create_from_options(options)

# Extract landmarks using the predefined function
landmarks = extract_landmarks(img_path)

if landmarks is None:
    print(f"No hand landmarks detected in image: {img_path}")
else:
    # Convert list of landmarks to numpy array and reshape for the model
    landmarks_array = np.array(landmarks).reshape(1, -1)

    # Scale the landmarks using the trained scaler
    scaled_landmarks = scaler.transform(landmarks_array)

    # Make prediction
    prediction = model.predict(scaled_landmarks)

    predicted_index = np.argmax(prediction)

    predicted_class = classes[predicted_index]

    confidence = np.max(prediction) * 100

    print("Prediction:", predicted_class)
    print("Confidence:", confidence)

classes = list(encoder.classes_)

# Dynamically find an image path from the 'waving' directory that has detectable landmarks
class_dir = os.path.join(extract_path, 'waving')

img_path = None
if os.path.exists(class_dir) and os.listdir(class_dir):
    for img_filename_candidate in os.listdir(class_dir):
        current_img_path = os.path.join(class_dir, img_filename_candidate)

        # Re-initialize MediaPipe HandLandmarker for each image check to ensure robustness
        import mediapipe as mp
        from mediapipe.tasks import python
        from mediapipe.tasks.python import vision

        base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
        options = vision.HandLandmarkerOptions(
            base_options=base_options,
            num_hands=1,
            min_hand_detection_confidence=0.5
        )
        global hand_landmarker # Declare global to modify the global variable
        hand_landmarker = vision.HandLandmarker.create_from_options(options)

        landmarks = extract_landmarks(current_img_path)

        if landmarks is not None:
            img_path = current_img_path
            break # Found an image with landmarks, break the loop

    if img_path is None:
        raise FileNotFoundError(f"Error: No images with detectable hand landmarks found in {class_dir}.")

else:
    raise FileNotFoundError(f"Error: Directory {class_dir} not found or is empty. Cannot find an image for prediction.")

print(f"Attempting to predict using image: {img_path}")

# If an image with landmarks was found, proceed with prediction
if landmarks is not None:
    # Convert list of landmarks to numpy array and reshape for the model
    landmarks_array = np.array(landmarks).reshape(1, -1)

    # Scale the landmarks using the trained scaler
    scaled_landmarks = scaler.transform(landmarks_array)

    # Make prediction
    prediction = model.predict(scaled_landmarks)

    predicted_index = np.argmax(prediction)

    predicted_class = classes[predicted_index]

    confidence = np.max(prediction) * 100

    print("Prediction:", predicted_class)
    print("Confidence:", confidence)
else:
    print(f"No hand landmarks detected in image: {img_path}. This message should not be reached if previous loop logic is correct.")

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# Define the classes based on the `encoder.classes_` from previous cells
classes = list(encoder.classes_)

# Dynamically find an image path from the 'greet' directory
# 'extract_path' is a global variable available from previous cells.
greet_dir = os.path.join(extract_path, 'greet')

img_path = None
# Check if the directory exists and is not empty
if os.path.exists(greet_dir) and os.listdir(greet_dir):
    for img_filename_candidate in os.listdir(greet_dir):
        current_img_path = os.path.join(greet_dir, img_filename_candidate)

        # Re-initialize MediaPipe HandLandmarker to ensure it's running
        base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
        options = vision.HandLandmarkerOptions(
            base_options=base_options,
            num_hands=1,
            min_hand_detection_confidence=0.5
        )
        global hand_landmarker # Declare global to modify the global variable
        hand_landmarker = vision.HandLandmarker.create_from_options(options)

        landmarks = extract_landmarks(current_img_path)

        if landmarks is not None:
            img_path = current_img_path
            break # Found an image with landmarks, break the loop

    if img_path is None:
        raise FileNotFoundError(f"Error: No images with detectable hand landmarks found in {greet_dir}.")
else:
    raise FileNotFoundError(f"Error: Directory {greet_dir} not found or is empty. Cannot find an image for prediction.")

print(f"Attempting to predict using image: {img_path}")

# Proceed with prediction if a suitable image with landmarks was found
if landmarks is not None:
    # Convert list of landmarks to numpy array and reshape for the model
    landmarks_array = np.array(landmarks).reshape(1, -1)

    # Scale the landmarks using the trained scaler
    scaled_landmarks = scaler.transform(landmarks_array)

    # Make prediction
    prediction = model.predict(scaled_landmarks)

    predicted_index = np.argmax(prediction)

    predicted_class = classes[predicted_index]

    confidence = np.max(prediction) * 100

    print("Prediction:", predicted_class)
    print("Confidence:", confidence)

    # For displaying, ensure the image is read correctly as well
    display_img = cv2.imread(img_path)
    if display_img is not None:
        plt.imshow(cv2.cvtColor(display_img, cv2.COLOR_BGR2RGB))
        plt.title(f"Predicted: {predicted_class} ({confidence:.2f}%) ")
        plt.axis('off')
        plt.show()
    else:
        print(f"Failed to read image for display from {img_path}.")
else:
    print(f"No hand landmarks detected in image: {img_path}. No prediction made.")

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# Define the classes based on the `encoder.classes_` from previous cells
classes = list(encoder.classes_)

# Dynamically find an image path from the 'pointing' directory
# 'extract_path' is a global variable available from previous cells.
pointing_dir = os.path.join(extract_path, 'pointing')

img_path = None
landmarks = None # Initialize landmarks outside the loop

# Check if the directory exists and is not empty
if os.path.exists(pointing_dir) and os.listdir(pointing_dir):
    for img_filename_candidate in os.listdir(pointing_dir):
        current_img_path = os.path.join(pointing_dir, img_filename_candidate)

        # Re-initialize MediaPipe HandLandmarker for each image check to ensure robustness
        base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
        options = vision.HandLandmarkerOptions(
            base_options=base_options,
            num_hands=1,
            min_hand_detection_confidence=0.5
        )
        global hand_landmarker # Declare global to modify the global variable
        hand_landmarker = vision.HandLandmarker.create_from_options(options)

        temp_landmarks = extract_landmarks(current_img_path)

        if temp_landmarks is not None:
            img_path = current_img_path
            landmarks = temp_landmarks # Assign the detected landmarks
            break # Found an image with landmarks, break the loop

    if img_path is None:
        raise FileNotFoundError(f"Error: No images with detectable hand landmarks found in {pointing_dir}.")
else:
    raise FileNotFoundError(f"Error: Directory {pointing_dir} not found or is empty. Cannot find an image for prediction.")

print(f"Attempting to predict using image: {img_path}")

# Proceed with prediction if a suitable image with landmarks was found
if landmarks is not None:
    # Convert list of landmarks to numpy array and reshape for the model
    landmarks_array = np.array(landmarks).reshape(1, -1)

    # Scale the landmarks using the trained scaler
    scaled_landmarks = scaler.transform(landmarks_array)

    # Make prediction
    prediction = model.predict(scaled_landmarks)

    predicted_index = np.argmax(prediction)

    predicted_class = classes[predicted_index]

    confidence = np.max(prediction) * 100

    print("Prediction:", predicted_class)
    print("Confidence:", confidence)

    # For displaying, ensure the image is read correctly as well
    display_img = cv2.imread(img_path)
    if display_img is not None:
        plt.imshow(cv2.cvtColor(display_img, cv2.COLOR_BGR2RGB))
        plt.title(f"Predicted: {predicted_class} ({confidence:.2f}%) ")
        plt.axis('off')
        plt.show()
    else:
        print(f"Failed to read image for display from {img_path}.")
else:
    print(f"No hand landmarks detected in image: {img_path}. No prediction made.")

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# Define the classes based on the `encoder.classes_` from previous cells
classes = list(encoder.classes_)

# Dynamically find an image path from the 'thumbs up' directory
# 'extract_path' is a global variable available from previous cells.
class_dir = os.path.join(extract_path, 'thumbs up')

img_path = None
landmarks = None # Initialize landmarks to store the result from extract_landmarks

# Check if the directory exists and is not empty
if os.path.exists(class_dir) and os.listdir(class_dir):
    for img_filename_candidate in os.listdir(class_dir):
        current_img_path = os.path.join(class_dir, img_filename_candidate)

        # Re-initialize MediaPipe HandLandmarker for each image check to ensure robustness
        base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
        options = vision.HandLandmarkerOptions(
            base_options=base_options,
            num_hands=1,
            min_hand_detection_confidence=0.5
        )
        global hand_landmarker # Declare global to modify the global variable
        hand_landmarker = vision.HandLandmarker.create_from_options(options)

        temp_landmarks = extract_landmarks(current_img_path)

        if temp_landmarks is not None:
            img_path = current_img_path
            landmarks = temp_landmarks # Assign the detected landmarks
            break # Found an image with landmarks, break the loop

    if img_path is None:
        raise FileNotFoundError(f"Error: No images with detectable hand landmarks found in {class_dir}.")
else:
    raise FileNotFoundError(f"Error: Directory {class_dir} not found or is empty. Cannot find an image for prediction.")

print(f"Attempting to predict using image: {img_path}")

# Proceed with prediction if a suitable image with landmarks was found
if landmarks is not None:
    # Convert list of landmarks to numpy array and reshape for the model
    landmarks_array = np.array(landmarks).reshape(1, -1)

    # Scale the landmarks using the trained scaler
    scaled_landmarks = scaler.transform(landmarks_array)

    # Make prediction
    prediction = model.predict(scaled_landmarks)

    predicted_index = np.argmax(prediction)

    predicted_class = classes[predicted_index]

    confidence = np.max(prediction) * 100

    print("Prediction:", predicted_class)
    print("Confidence:", confidence)

    # For displaying, ensure the image is read correctly as well
    display_img = cv2.imread(img_path)
    if display_img is not None:
        plt.imshow(cv2.cvtColor(display_img, cv2.COLOR_BGR2RGB))
        plt.title(f"Predicted: {predicted_class} ({confidence:.2f}%) ")
        plt.axis('off')
        plt.show()
    else:
        print(f"Failed to read image for display from {img_path}.")
else:
    print(f"No hand landmarks detected in image: {img_path}. No prediction made.")

classes = list(encoder.classes_)

# Dynamically find an image path from the 'thumbs up' directory
class_dir = os.path.join(extract_path, 'thumbs up')

img_path = None
# Check if the directory exists and is not empty
if os.path.exists(class_dir) and os.listdir(class_dir):
    # Get the first image filename in the 'thumbs up' directory
    img_filename = os.listdir(class_dir)[0]
    img_path = os.path.join(class_dir, img_filename)
else:
    raise FileNotFoundError(f"Error: Directory {class_dir} not found or is empty. Cannot find an image for prediction.")

print(f"Attempting to predict using image: {img_path}")

# Re-initialize MediaPipe HandLandmarker to ensure it's running
# This addresses potential issues where the global hand_landmarker might have been closed
# or an inconsistent kernel state led to the 'Task runner is currently not running' error.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
options = vision.HandLandmarkerOptions(
    base_options=base_options,
    num_hands=1,
    min_hand_detection_confidence=0.5
)
global hand_landmarker # Declare global to modify the global variable
hand_landmarker = vision.HandLandmarker.create_from_options(options)

# Extract landmarks using the predefined function
landmarks = extract_landmarks(img_path)

if landmarks is None:
    print(f"No hand landmarks detected in image: {img_path}")
else:
    # Convert list of landmarks to numpy array and reshape for the model
    landmarks_array = np.array(landmarks).reshape(1, -1)

    # Scale the landmarks using the trained scaler
    scaled_landmarks = scaler.transform(landmarks_array)

    # Make prediction
    prediction = model.predict(scaled_landmarks)

    predicted_index = np.argmax(prediction)

    predicted_class = classes[predicted_index]

    confidence = np.max(prediction) * 100

    print("Prediction:", predicted_class)
    print("Confidence:", confidence)

train_acc = history.history['accuracy'][-1] * 100

val_acc = history.history['val_accuracy'][-1] * 100

print(f"Training Accuracy: {train_acc:.2f}%")

print(f"Validation Accuracy: {val_acc:.2f}%")

# STEP 17 — Confusion Matrix
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,6))

sns.heatmap(cm, annot=True, fmt='d')

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

# MODEL 2 — Random Forest Baseline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(n_estimators=100)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

rf_acc = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_acc*100)

# STEP 18 — Save Model
# Save .h5 Model
model.save("gesture_model.h5")

# STEP 19 — Save Label Encoder
import pickle

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(encoder, f)

# STEP 20 — Save Scaler
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

# STEP 21 — Convert to TFLite (OPTIONAL)
import tensorflow as tf

# Lightweight mobile version.

converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()

with open("gesture_model.tflite", "wb") as f:
    f.write(tflite_model)

import mediapipe as mp

mp.solutions.hands

mp_hands = mp.solutions.hands

hands = mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=1,
    min_detection_confidence=0.5
)

mp_draw = mp.solutions.drawing_utils

!pip install mediapipe==0.10.14

# REAL-TIME INFERENCE USING WEBCAM
# STEP 22 — Live Webcam Prediction
import cv2
import mediapipe as mp # Still need this for mp.Image
import numpy as np
import pickle
from tensorflow.keras.models import load_model
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# Using direct mp.solutions access as observed in successfully executed cell Tpb9SCKif_Js
# This addresses the previous ModuleNotFoundError for 'mediapipe.python' and ensures consistency with working code.
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands # Needed for HAND_CONNECTIONS
from mediapipe.framework.formats import landmark_pb2 # This import was already working

# Load model
model = load_model("gesture_model.h5")

# Load encoder
with open("label_encoder.pkl", "rb") as f:
    encoder = pickle.load(f)

# Load scaler
with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

# Initialize MediaPipe HandLandmarker for live stream
base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
options = vision.HandLandmarkerOptions(
    base_options=base_options,
    num_hands=1,
    min_hand_detection_confidence=0.5,
    running_mode=vision.RunningMode.IMAGE # For processing individual frames
)
hand_landmarker = vision.HandLandmarker.create_from_options(options)


# Webcam
cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()

    if not ret:
        break

    # Convert the BGR image to RGB and then to MediaPipe Image format
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame_rgb)

    # Perform hand landmark detection
    detection_result = hand_landmarker.detect(mp_image)

    if detection_result.hand_landmarks:

        for hand_landmarks_proto in detection_result.hand_landmarks:

            landmarks = []

            for lm in hand_landmarks_proto:

                landmarks.append(lm.x)

                landmarks.append(lm.y)

            landmarks = np.array(landmarks).reshape(1, -1)

            landmarks = scaler.transform(landmarks)

            prediction = model.predict(landmarks)

            predicted_class = np.argmax(prediction)

            gesture = encoder.inverse_transform([predicted_class])[0]

            confidence = np.max(prediction) * 100

            # Draw landmarks
            # Convert the list of NormalizedLandmark objects to a NormalizedLandmarkList
            # This is required by mp_drawing.draw_landmarks as it expects the old format.
            landmark_list = landmark_pb2.NormalizedLandmarkList(
                landmark=[landmark_pb2.NormalizedLandmark(x=lm.x, y=lm.y, z=lm.z) for lm in hand_landmarks_proto]
            )

            mp_drawing.draw_landmarks(
                frame,
                landmark_list, # Now passing a proper NormalizedLandmarkList
                mp_hands.HAND_CONNECTIONS, # Using mp_hands.HAND_CONNECTIONS from explicit import
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style()
            )

            # Show prediction
            cv2.putText(
                frame,
                f'{gesture} ({confidence:.2f}%)',
                (10, 40),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (0,255,0),
                2
            )

    cv2.imshow("Hand Gesture Recognition", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
hand_landmarker.close() # Close the HandLandmarker to release resources

!pip install gradio

import gradio as gr

def predict_image(image):

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    results = hands.process(image_rgb)

    if not results.multi_hand_landmarks:
        return "No Hand Detected"

    landmarks = []

    hand_landmarks = results.multi_hand_landmarks[0]

    for lm in hand_landmarks.landmark:

        landmarks.append(lm.x)

        landmarks.append(lm.y)

    landmarks = np.array(landmarks).reshape(1, -1)

    landmarks = scaler.transform(landmarks)

    prediction = model.predict(landmarks)

    predicted_class = np.argmax(prediction)

    gesture = encoder.inverse_transform([predicted_class])[0]

    confidence = np.max(prediction) * 100

    return f"Gesture: {gesture}\\nConfidence: {confidence:.2f}%"

import gradio as gr
from tensorflow.keras.models import load_model
import numpy as np
import cv2
import pickle
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# Load the trained Keras model
model = load_model('gesture_model.h5')

# Load the LabelEncoder and StandardScaler
with open('label_encoder.pkl', 'rb') as f:
    encoder = pickle.load(f)

with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

classes = list(encoder.classes_)

# Initialize MediaPipe HandLandmarker globally for the Gradio app
base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
options = vision.HandLandmarkerOptions(
    base_options=base_options,
    num_hands=1,
    min_hand_detection_confidence=0.5
)
hand_landmarker = vision.HandLandmarker.create_from_options(options)

def extract_landmarks_for_gradio(image_np):
    """
    Extracts hand landmarks from a numpy image array using MediaPipe HandLandmarker.
    This is a local version for Gradio to avoid saving temporary files.
    """
    # Convert the BGR image (from Gradio) to RGB and then to MediaPipe Image format
    image_rgb = cv2.cvtColor(image_np, cv2.COLOR_BGR2RGB)
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image_rgb)

    # Perform hand landmark detection
    detection_result = hand_landmarker.detect(mp_image)

    # Check if any hand landmarks were detected
    if not detection_result.hand_landmarks:
        return None

    landmarks = []
    # We are interested in the first detected hand
    hand_landmarks = detection_result.hand_landmarks[0]

    for lm in hand_landmarks:
        landmarks.append(lm.x)
        landmarks.append(lm.y)

    return landmarks

def predict_gesture(image):
    # `image` here is a numpy array from Gradio's Image input

    landmarks = extract_landmarks_for_gradio(image)

    if landmarks is None:
        return "No Hand Detected or Landmarks Extracted."

    # Convert list of landmarks to numpy array and reshape for the model
    landmarks_array = np.array(landmarks).reshape(1, -1)

    # Scale the landmarks using the trained scaler
    scaled_landmarks = scaler.transform(landmarks_array)

    # Make prediction
    prediction = model.predict(scaled_landmarks)

    predicted_index = np.argmax(prediction)

    predicted_class = classes[predicted_index]

    confidence = float(np.max(prediction) * 100)

    return f"Prediction: {predicted_class}\nConfidence: {confidence:.2f}%"


interface = gr.Interface(
    fn=predict_gesture,
    inputs=gr.Image(type='numpy'),
    outputs='text',
    title='Hand Gesture Recognition',
    description='Upload an image containing a hand gesture for prediction.'
)

interface.launch(share=True)

import gradio as gr
import cv2
import mediapipe as mp
import numpy as np
import pickle
from tensorflow.keras.models import load_model

# =========================
# LOAD MODEL
# =========================

model = load_model("gesture_model.h5")

# =========================
# LOAD LABEL ENCODER
# =========================

with open("label_encoder.pkl", "rb") as f:
    encoder = pickle.load(f)

# =========================
# LOAD SCALER
# =========================

with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

# =========================
# MEDIAPIPE HANDS
# =========================

mp_hands = mp.solutions.hands

hands = mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=1,
    min_detection_confidence=0.3
)

mp_draw = mp.solutions.drawing_utils

# =========================
# PREDICTION FUNCTION
# =========================

def predict_gesture(image):

    try:

        # Check image
        if image is None:
            return "No Image Uploaded"

        # Convert image properly
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        # Flip image (optional)
        image = cv2.flip(image, 1)

        # Resize image
        image = cv2.resize(image, (640, 480))

        # Convert to RGB for MediaPipe
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Process image
        results = hands.process(image_rgb)

        # No hand detected
        if not results.multi_hand_landmarks:
            return "No Hand Detected Properly"

        # Get landmarks
        landmarks = []

        hand_landmarks = results.multi_hand_landmarks[0]

        for lm in hand_landmarks.landmark:

            landmarks.append(lm.x)
            landmarks.append(lm.y)

        # Convert to numpy
        landmarks = np.array(landmarks).reshape(1, -1)

        # Scale features
        landmarks = scaler.transform(landmarks)

        # Prediction
        prediction = model.predict(landmarks, verbose=0)

        predicted_index = np.argmax(prediction)

        confidence = np.max(prediction) * 100

        # Get label
        gesture = encoder.inverse_transform([predicted_index])[0]

        # Final result
        result = f"""
Prediction: {gesture}

Confidence: {confidence:.2f}%
"""

        return result

    except Exception as e:
        return f"Error: {str(e)}"

# =========================
# GRADIO INTERFACE
# =========================

interface = gr.Interface(

    fn=predict_gesture,

    inputs=gr.Image(type="numpy"),

    outputs="text",

    title="Hand Gesture Recognition System",

    description="""
Upload a hand gesture image.
Supported Gestures:
- greet
- pointing
- thumbs up
- waving
"""
)

# =========================
# LAUNCH
# =========================

interface.launch(share=True)

!pip install streamlit pyngrok mediapipe

!streamlit run app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import cv2
# import mediapipe as mp
# import numpy as np
# import pickle
# from tensorflow.keras.models import load_model
# from mediapipe.tasks import python
# from mediapipe.tasks.python import vision
# 
# st.set_page_config(layout="wide")
# 
# # =========================
# # LOAD MODEL, ENCODER, SCALER
# # =========================
# 
# @st.cache_resource
# def load_artifacts():
#     model = load_model("gesture_model.h5")
#     with open("label_encoder.pkl", "rb") as f:
#         encoder = pickle.load(f)
#     with open("scaler.pkl", "rb") as f:
#         scaler = pickle.load(f)
#     return model, encoder, scaler
# 
# model, encoder, scaler = load_artifacts()
# classes = list(encoder.classes_)
# 
# # =========================
# # MEDIAPIPE HANDLANDMARKER INITIALIZATION
# # =========================
# 
# @st.cache_resource
# def init_hand_landmarker():
#     base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
#     options = vision.HandLandmarkerOptions(
#         base_options=base_options,
#         num_hands=1,
#         min_hand_detection_confidence=0.5,
#         running_mode=vision.RunningMode.IMAGE # For processing individual frames
#     )
#     return vision.HandLandmarker.create_from_options(options)
# 
# hand_landmarker = init_hand_landmarker()
# 
# # =========================
# # LANDMARK EXTRACTION FUNCTION
# # =========================
# 
# def extract_landmarks(image_np):
#     image_rgb = cv2.cvtColor(image_np, cv2.COLOR_BGR2RGB)
#     mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image_rgb)
#     detection_result = hand_landmarker.detect(mp_image)
# 
#     if not detection_result.hand_landmarks:
#         return None
# 
#     landmarks = []
#     for lm in detection_result.hand_landmarks[0]:
#         landmarks.append(lm.x)
#         landmarks.append(lm.y)
#     return landmarks
# 
# # =========================
# # PREDICTION FUNCTION
# # =========================
# 
# def predict_gesture(image_np):
#     landmarks = extract_landmarks(image_np)
# 
#     if landmarks is None:
#         return "No Hand Detected or Landmarks Extracted."
# 
#     landmarks_array = np.array(landmarks).reshape(1, -1)
#     scaled_landmarks = scaler.transform(landmarks_array)
#     prediction = model.predict(scaled_landmarks, verbose=0)
# 
#     predicted_index = np.argmax(prediction)
#     predicted_class = classes[predicted_index]
#     confidence = float(np.max(prediction) * 100)
# 
#     return f"Prediction: {predicted_class}\nConfidence: {confidence:.2f}%"
# 
# # =========================
# # STREAMLIT INTERFACE
# # =========================
# 
# st.title("Hand Gesture Recognition System")
# st.write("Upload an image containing a hand gesture for prediction.")
# st.write("Supported Gestures: greet, pointing, thumbs up, waving")
# 
# uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])
# 
# if uploaded_file is not None:
#     # Read the image file
#     file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
#     image = cv2.imdecode(file_bytes, 1)
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.image(image, caption='Uploaded Image', use_column_width=True, channels="BGR")
# 
#     with col2:
#         if st.button('Predict Gesture'):
#             result = predict_gesture(image)
#             st.success(result)
# 
# st.markdown("---")
# st.markdown("Developed using TensorFlow, MediaPipe, and Streamlit.")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import cv2
# import mediapipe as mp
# import numpy as np
# import pickle
# from tensorflow.keras.models import load_model
# from PIL import Image
# 
# # =========================
# # PAGE TITLE
# # =========================
# 
# st.title("Hand Gesture Recognition System")
# 
# st.write("Upload a hand gesture image")
# 
# # =========================
# # LOAD MODEL
# # =========================
# 
# model = load_model("gesture_model.h5")
# 
# # =========================
# # LOAD ENCODER
# # =========================
# 
# with open("label_encoder.pkl", "rb") as f:
#     encoder = pickle.load(f)
# 
# # =========================
# # LOAD SCALER
# # =========================
# 
# with open("scaler.pkl", "rb") as f:
#     scaler = pickle.load(f)
# 
# # =========================
# # MEDIAPIPE HANDS
# # =========================
# 
# mp_hands = mp.solutions.hands
# 
# hands = mp_hands.Hands(
#     static_image_mode=True,
#     max_num_hands=1,
#     min_detection_confidence=0.3
# )
# 
# # =========================
# # IMAGE UPLOAD
# # =========================
# 
# uploaded_file = st.file_uploader(
#     "Choose Image",
#     type=["jpg", "png", "jpeg"]
# )
# 
# # =========================
# # PREDICTION
# # =========================
# 
# if uploaded_file is not None:
# 
#     image = Image.open(uploaded_file)
# 
#     image = np.array(image)
# 
#     st.image(image, caption="Uploaded Image")
# 
#     image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
# 
#     image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
# 
#     results = hands.process(image_rgb)
# 
#     if not results.multi_hand_landmarks:
# 
#         st.error("No Hand Detected")
# 
#     else:
# 
#         landmarks = []
# 
#         hand_landmarks = results.multi_hand_landmarks[0]
# 
#         for lm in hand_landmarks.landmark:
# 
#             landmarks.append(lm.x)
#             landmarks.append(lm.y)
# 
#         landmarks = np.array(landmarks).reshape(1, -1)
# 
#         landmarks = scaler.transform(landmarks)
# 
#         prediction = model.predict(landmarks)
# 
#         predicted_index = np.argmax(prediction)
# 
#         confidence = np.max(prediction) * 100
# 
#         gesture = encoder.inverse_transform(
#             [predicted_index]
#         )[0]
# 
#         st.success(f"Prediction: {gesture}")
# 
#         st.info(f"Confidence: {confidence:.2f}%")

!pip install pyngrok

from pyngrok import ngrok
import os

# IMPORTANT: Replace 'YOUR_AUTH_TOKEN' with your actual ngrok authtoken.
# You can get it from https://dashboard.ngrok.com/get-started/your-authtoken
# You might also need to set an environment variable or manually paste the token.
# For example:
# from getpass import getpass
# authtoken = getpass('Enter your ngrok authtoken:')
# ngrok.set_auth_token(authtoken)
# For a simpler approach, if you have your token as a string:
# ngrok.set_auth_token("YOUR_AUTH_TOKEN")
# For demonstration purposes, we will use a placeholder. Please replace it.
# You can also set it as an environment variable (NGROK_AUTH_TOKEN) for security.
# In Colab, you could do: !echo "NGROK_AUTH_TOKEN=YOUR_AUTH_TOKEN" > .env
# and then os.environ.get('NGROK_AUTH_TOKEN')

# --- Placeholder for authtoken setup ---
# You should uncomment and replace 'YOUR_AUTH_TOKEN' with your actual token
ngrok.set_auth_token("3DdDzOPT9DkMdUyxbJpQalyRETY_iNEgtgRtH6tyLS8cpkLM")
# --- End Placeholder ---

# Start streamlit
get_ipython().system_raw('streamlit run app.py --server.port 8501 &')

# Create public URL
# This line will only work after ngrok is authenticated
public_url = ngrok.connect(8501)

print(public_url)